"""initial migration

Revision ID: bd85ca424a71
Revises: 
Create Date: 2026-06-29 11:16:52.691494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd85ca424a71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
